### ISSUE TITLE
Hayes' first dialog after the audio distortion effect gets skipped when OpenAL is being used

### ISSUE THREAD

**Issue by onpon4** [JHGuitarFreak/UQM-MegaMod#111]
Interesting little glitch I ran into: when I was talking to Hayes while the audio and screen were distorted, at the point where it switched the distortion off ("Now, as soon as our engineers can refit the energy cores…"), the progress bar kept animating forward, but the game otherwise acted as if the rest of the dialog had been skipped (showed the next options, Hayes stopped talking, and reversing with left arrow brought it to the line before the last one). This for me happens consistently, though I don't know if this is dependent on use of optional packages (I have many enabled) or on particular settings.

🦇

**Comment by JHGuitarFreak** [comment]
I'll have to test it out. But it could be related to the use of an alternative music track in Vol's remix pack.

**Comment by onpon4** [comment]
Huh, well if it could be music, I chose not to install that remix pack, and I have the Precursors remixes enabled.

🦇

**Comment by JHGuitarFreak** [comment]
Hmmmm... 

I'll test with different remix packs enabled then. Could be more than one if it's doing it with the Precursors Remix pack.

**Comment by JHGuitarFreak** [comment]
I can not replicate this on my end at all.

Even when using the v0.8.1 release version. 

Perhaps post your settings and the save file.

**Comment by onpon4** [comment]
Sure! I'll just attach all the possibly relevant ones under ~/.uqm-megamod.

[megamod-config.tar.gz](https://github.com/JHGuitarFreak/UQM-MegaMod/files/8885464/megamod-config.tar.gz)

The save I have is just a new game (not actually at the point where it happens), but all I did was just the normally expected tutorial stuff (talk to Hayes, go to Mercury to get radioactives, talk to Hayes again).

🦇

**Comment by JHGuitarFreak** [comment]
Something funky is going on because this is the first time *anything* different happened.  
Hayes' dialog got a bit jumpy after the radioactives. And that was with no remixes.

I'll edit this comment with updates on what I find.

UPDATE:

Can you try switching the sound driver to MixSDL (in the sound settings)?  
That seems to fix it for me.

Though I've no idea why it being OpenAL would screw up that one spot.

**Comment by onpon4** [comment]
I can confirm that using MixSDL instead of OpenAL avoids the problem. Strange indeed, I never would've guessed that could cause the issue. I suppose I'll play with MixSDL, then (not sure how much benefit UQM gets from OpenAL so I probably won't be missing much).

🦇

**Comment by JHGuitarFreak** [comment]
The kicker is that this is a MegaMod only bug. Tried it in vanilla UQM and OpenAL works just fine.

I'm not too bothered by the bug if the only spot affected is Hayes' post-radios dialog.

**Comment by JoshuaPettus** [comment]
Question, what does OpenAL offer over MixSDL?  Especially for most of us with regular built-in stereo sound?  Couldn't you just put the (experimental) text right next to the OpenAL setting (I believe it says so in the build script) and default to MixSDL. 

 Or, would it even be bad to remove OpenAL entirely just to simplify the headache?

**Comment by onpon4** [comment]
It already defaults to MixSDL (and so does UQM), probably specifically because of issues like this (OpenAL can cause all kinds of audio problems even in vanilla UQM depending on where you're running it, this isn't even the worst of them). I enabled OpenAL anyway intentionally. It's mostly out of habit at this point, but the original reason I started doing that is because UQM's audio used to lag visuals quite badly when MixSDL was used and OpenAL didn't have this problem. That doesn't seem to be a problem anymore though. I think OpenAL also enables some other minor features, though I'm not sure about that.

In any case, there's probably no need to remove it outright, the build script won't even include support for it unless you tell it to and it's very clear about the fact that OpenAL is in an "experimental" state. This particular bug was just one that made it less obvious that OpenAL was the problem.

🦇

**Comment by JHGuitarFreak** [comment]
OpenAL was previously the only way to get positional audio. Then Ala-lala fixed it up so that MixSDL could also have positional audio.

To my ears OpenAL also sounds lower quality.

> but the original reason I started doing that is because UQM's audio used to lag visuals quite badly when MixSDL was used and OpenAL didn't have this problem.

I'm willing to bet the reason this doesn't happen anymore is the switch to SDL2 which makes better use of hardware acceleration.

**Comment by JHGuitarFreak** [comment]
Did some testing and this bug still happens in the latest version of MegaMod but only in OpenAL and only if you use the distorted audio files (Which is now not the default nor is it an add-on).

What this leads me to believe is that the audio files themselves are causing the problem...

...And having converted the distorted audio files to the proper frequency, channel, and bitrate there's no more audio artifacts or jumping around like there was previously.  

I'm including here the files specifically affected so that anyone coming across this before the next release can plop them into their 3DO Voice addon.

[commander-distorted-audio.zip](https://github.com/user-attachments/files/17140416/commander-distorted-audio.zip)

Closing the issue.
