### ISSUE TITLE
Hard mode Sa-Matra seems poorly balanced

### ISSUE THREAD

**Issue by onpon4** [JHGuitarFreak/UQM-MegaMod#121]
I was playing through hard mode and I'm finding the Sa-Matra battle… too difficult, and not in a good way.

Speaking as a game designer, I feel a major mistake has been made here, something you might call the "Kaizo Trap". When I first saw that the Sa-Matra battle was made "harder" in the changelog, I was very interested because the original is kind of anticlimactic. But the way that the Sa-Matra battle has been made harder I believe has gone in the opposite direction of being so frustrating, that I don't think I'll be finishing this game. I tried with all the ships available to me that make sense, including the Yehat and Pkunk ships that are supposed to be your "rescue" or trump card against the Sa-Matra, and I can scarcely even get one of the shield generator things destroyed. It feels like no matter what I do, every ship is sub-optimal in the fight and I'm expected to play the game like a TAS, with perfect RNG and perfect reflexes.

Thing is, in game design, what is often important isn't so much how hard it is as how *epic* it is, and this is especially true for a final battle. Final battles aren't supposed to be hard, they're supposed to feel like an accomplishment that caps off the game. That does require difficulty in most (but not all) cases, but insurmountable or unreasonable difficulty is just annoying. To explain why I think hard mode is making this mistake, I'd like to describe my experience with all of the ships I attempted to use:

* Chmmr: Can't approach the Sa-Matra because the green things bounce you around, meanwhile the fireballs kill you.
* Utwig: Green things immediately drain all of your shield, then the fireballs kill you before you can even think of approaching the Sa-Matra.
* Shofixti: Stray fireball kills you before you can get even close to the Sa-Matra, preventing use of the Glory Device to do anything but damage the endless projectiles.
* Yehat: Green things drain your shield, fireballs instakill you if you don't have your shield on constantly. Only possible way to survive is to get hit by the green things in just the right way and at just the right time to both start rocketing across faster than the fireballs (or at least not much slower), while not getting destroyed by a fireball when you're attempting to get hit by them or are vulnerable. Once you do that, you have to drift along and wait long periods of time hoping to get close to the Sa-Matra so you can shoot at it.
* Pkunk: Can dodge the fireballs in theory with maneuvering, but inevitably the green things get in your way and force you to take a hit. Approaching the Sa-Matra is almost impossible in the chaos, and in the rare event that you make it to the Sa-Matra, you can only inflict a tiny amount of damage.

Thing is, even in the vanilla game, the Sa-Matra is pretty unreasonable, and it's really only by making use of the Pkunk that it's made easy. The changes made for hard mode to make the Sa-Matra harder not only eliminate that key to victory intended in the original design, they also make dealing with it with other ships even less feasible, primarily because of the new energy draining effect of the green things. I genuinely don't see any reason for it to go that far, and also, leaving no key to victory at all robs the fight of any positive experience you can get out of it.

I would suggest that, if you want to make the Sa-Matra harder, it would be a far better thing to make design changes to how the fight works, instead of just keeping it the same but speeding up the Sa-Matra's projectiles. If it's going to be kept fundamentally the same, this level of difficulty increase is, I would argue, excessive. Compared to vanilla, the only change I can think of that might be OK is speeding up the green things a bit (while leaving the fireballs at their original speed), and even that might be too much.

I don't have any specific ideas for design changes to make it harder in a better way, but I'd suggest, if you attempt this, thinking of it as a puzzle, with the Yahat and Pkunk ships as the solution. Think about what problem the player should solve, and how the Yehat and Pkunk ships are perfectly tailored to solve it. In the original, the Pkunk ship is perfectly tailored to solve the puzzle for the simple reason that it's faster than any of the projectiles that get spit out, and the Yehat ship is perfectly tailored to solve the puzzle because it has powerful, easy to aim guns that can clear the way for a safe entry by the flagship. Any attempt to make the fight harder needs to also do something like that, just perhaps in a different way that requires some more skill.

**Comment by JHGuitarFreak** [comment]
I think I'm gonna meet you halfway on this and nerf the projectile speeds back to normal.  
There's really no good way to make it enjoyably harder without rewriting how the battle works and that's just not in the cards.

This way you can still outrun them using the same methods as the original but now you have to think about where you're going.

**Comment by Kruzen** [comment]
I think you’ve just played poorly with the pkunk. Applying your own advice, you failed to solve the puzzle. Fury can easily outmaneuver fire comets as much as you want.

Now… What do we want with Hard mode? I think - to challenge veteran players, not making the game more cinematic. You cannot make sa-matra epic without completely remaking the fight. According to the original balance philosophy: star control is balanced around fleets, not ships. Therefore you have rock/paper/scissors scenario all over the place. However being paper against scissors puts you into disadvantage here instead of instant loss. So it is ok that sa-matra obliterates some ships. More lore-accurate I must say. But let’s analyze it. If sa-matra is scissors, then you have 4 rocks to defeat it reliably. And don’t try to convince me that 12 shof is a valid strat. It’s for extra challenge to spice original fight. The 4 rocks are: Pkunk, Utwig, Chmmr, Yehat. We cannot rebalance ships, so let’s upgrade our scissors. That way we challenge the player by making said rocks less effective. In the same way paper ships becoming even less effective, so no gimmicks. However building your fleet correctly is part of a skillset. It is ok to not have supox here for instance.

So, the rocks. 3 of 4 ships are strong because they can tank incoming damage. Yehat and utwig by their shields, and chmmr by massive health pool. Chmmr having low thrust and useless special in that fight makes it weak against green globes as you cannot approach generators reliably and hit them with very narrow lasers. But zapsats can compensate that. 

Yehat and Utwig have a wide spread weapons and can propulse themselves with green globes while shield is up.

But Fury is OP here. It can outrun any projectile making it effectively invulnerable. Making comets the same speed as fury still has no effect as they can’t reach it. Nerfing comet speed back is like going to square 1. 

If we want the same 4 ships being reliable (which imo weird… original fight is boring, but we want the same way of solving it in a hard mode) I suggest to nerf green globes. Especially their HP. Yes, less in HM than in vanilla. That way Yehat and Utwig can shot them down before energy drain occurs. Chmmr destroys them with zapsats making player concentrate on aiming and tanking comet damage. And adjust energy drain depending on how effectively they are destroyed (1 instead of 2). Speeding them up is nonsense! Their purpose is area denial. They cannot be fast by their nature. But don’t revert comet speed! It will make Fury nuts again. You can spawn 100 comets - that won’t make any difference without speed boost.

I’ll be back in the next week, we can discuss that in more detail.

**Comment by onpon4** [comment]
> I think you’ve just played poorly with the pkunk. Applying your own advice, you failed to solve the puzzle. Fury can easily outmaneuver fire comets as much as you want.
>
> Now… What do we want with Hard mode? I think - to challenge veteran players, not making the game more cinematic.

Thanks for implying that I'm just a noob who needs to "get good" even though I've beaten the vanilla game dozens of times and know it like the back of my hand, and even wrote a guide for the no-starbase challenge while I beat that challenge years ago. /s

Regarding your claim that the Fury can "easily outmaneuver" the comets, that assumes that you managed to not get into a position where turning left and right causes you to slam into the green projectiles, and it still doesn't help the fact that you need to hit the orbs around the Sa-Matra dozens of times with the Pkunk weapons for that to even be helpful.

In fact, there *is* a ship that I believe likely can easily outmaneuver everything, but I haven't mentioned that ship (and didn't even bother trying it) because it's a terrible choice if you actually want to have fun: the Thraddash. That ship is so ridiculously fast that there's no way you could ever make the Sa-Matra fight (as it works in vanilla) impossible to cheese; just use the afterburner to escape all projectiles and wither the thing away with the peashooter from a distance.

> If we want the same 4 ships being reliable (which imo weird… original fight is boring, but we want the same way of solving it in a hard mode) I suggest to nerf green globes. Especially their HP. Yes, less in HM than in vanilla. That way Yehat and Utwig can shot them down before energy drain occurs. Chmmr destroys them with zapsats making player concentrate on aiming and tanking comet damage. And adjust energy drain depending on how effectively they are destroyed (1 instead of 2). Speeding them up is nonsense! Their purpose is area denial. They cannot be fast by their nature. But don’t revert comet speed! It will make Fury nuts again. You can spawn 100 comets - that won’t make any difference without speed boost.

I don't agree with your calculation that the Chmmr, Yehat, and Utwig ships are "paper" against a Sa-Matra which is "rock". The Sa-Matra fight is designed in such a way that it basically overrides the whole rock-paper-scissors gameplay. If we keep using the rock-paper-scissors analogy, then the Sa-Matra is dynamite, and narratively, this makes sense. Any ship you throw at it in vanilla will barely be able to do anything against it. The one major exception designed in is Pkunk, which conveniently comes to you as reinforcements if you complete the Yehat rebellion quest, so narratively, that also makes sense: the Pkunk and Yehat save you from certain death at just the last moment (it's even foreshadowed by the Pkunk).

I'm repeating myself, but the Sa-Matra isn't supposed to be a hard fight. It's supposed to be a nearly impossible fight, but one that has a special trick to solving it, and *that* is where it gets its difficulty from: it's a puzzle, and the solution is to either bring a Pkunk in or complete the optional Yehat rebellion quest.

If you take away the Pkunk's ability to easily beat the fight, then the Yehat rebellion subplot isn't anywhere near as significant, because at that point all you're getting is just another ship in a nearly impossible fight. All that narrative purpose is thrown out the window. The only way this can be made okay is if you flip the script so that the Yehat ships are the ones that counter the Sa-Matra, but the best way to do that would be to make the green things faster but keep everything else unchanged, the opposite of what you're proposing here.

Personally, I'm perfectly fine with Pkunk staying as the solution against the Sa-Matra, and I'd be happy with the compromise of keeping the projectiles stronger (thus making it even more impossible to beat with most ships), but at original speed (thus allowing Pkunk to outrun the projectiles easily). The Sa-Matra fight isn't designed to be a challenge, but you can always challenge yourself (as I have done so many times in the vanilla game) by refusing to use a Pkunk ship in the fight. Heck, hard mode already makes the intended solution harder by making the Yehat rebellion quest harder.

🦇

**Comment by Kruzen** [comment]
Yes. I managed to beat it with Fury not even losing a single crew member. Because I was polishing values for almost 2 weeks and in the end I thought to buff it even more but decided not to. 

I didn’t beat no starbase run and played real pvp battle once. So I thought me being slightly above average melee player (I can beat AI without lot of problems) assured that anyone more skillful than me can crack this with no sweat.

I don’t think I need to explain to you why Thradd being at least as maneuverable as Pkunk doesn’t make it a solution. And I don’t need to remind you that you acquire Furies automatically when you get the spindle. You just need to keep them till the end. Yehat revolution is still not required.

Overall, I don’t get anything you’re saying. It’s like subconscious stream of thoughts. Everything contradicts with the conclusions I’ve made. You want the fight to be nearly impossible but complain you can’t beat it with one of the weakest ships.  You want it to be dynamite but at the same time fury must beat it with no sweat. Yes, hardmode sa-matra is hard and fury can beat it.

The only non-abstract and non-subjective suggestion you’ve made is to speed up green sentries. If you’re a game designer then you know that stun mechanics are bane of games. And sentries do just that - send you into a different direction. Player is punished by getting into space they occupy. More speed means more space to avoid which is frustrating because it’s out of player’s control for the most part. And no - avoiding comets is not the same - you’re not losing control therefore you can still plan your way without disturbance.

**Comment by onpon4** [comment]
> Yes. I managed to beat it with Fury not even losing a single crew member. Because I was polishing values for almost 2 weeks and in the end I thought to buff it even more but decided not to.
>
> I didn’t beat no starbase run and played real pvp battle once. So I thought me being slightly above average melee player (I can beat AI without lot of problems) assured that anyone more skillful than me can crack this with no sweat.

Did you design this, then? If so, you failed to consider two very important things:

1. The Sa-Matra battle is not comparable to normal battles, so normal skill in normal combat is not at all a good predictor of success with these changes.
2. When you're the designer of something, you *always* are going to be substantially better at it than other players. You say you were "polishing values" for almost 2 weeks; well, that's almost 2 weeks practicing the same fight over and over again. You being able to then win without taking damage means nothing in the grand scheme of how reasonable the difficulty is when you take that into account.

> I don’t think I need to explain to you why Thradd being at least as maneuverable as Pkunk doesn’t make it a solution.

The only reason it's not a solution is because it isn't fun to play. The Mark VI blaster *can* defeat the Sa-Matra, it would just take forever to accomplish. I was not proposing it as a solution, but pointing out that attempting to make the Sa-Matra impossible to cheese is a virtually unattainable goal.

> And I don’t need to remind you that you acquire Furies automatically when you get the spindle. You just need to keep them till the end. Yehat revolution is still not required.

Yes, I know that (and even mentioned it, so I don't know why you would bring it up), but it still factors into how easy or difficult the fight is. Puzzles, by their nature, are always easier when you know the solution. That doesn't make them deficient in their design.

> You want the fight to be nearly impossible but complain you can’t beat it with one of the weakest ships. You want it to be dynamite but at the same time fury must beat it with no sweat. Yes, hardmode sa-matra is hard and fury can beat it.

This statement horribly misconstrues what I said. What I said is that, in the vanilla game, the fight *is* nearly impossible, *but* that there's a special solution in the form of the Pkunk.

I'm not interested in the fact that the Pkunk *can* beat the Sa-Matra as it is in hard mode. Ships other than the Pkunk also *can* beat the Sa-Matra in the vanilla game (and I've done so before in challenge runs). That's not the point; the point is if there's no solution (e.g. the easy win via Pkunk in the vanilla game), then the fight is frustrating. It's not hard in a good way.

> If you’re a game designer then you know that stun mechanics are bane of games.

That's not true, and if that's your understanding of game design, you have a lot to learn. Game design is far, far more complex than certain mechanics being universally good and certain mechanics being universally bad. Everything has to be taken together in context to know whether the design is good or bad. Some of my favorite games (like Final Fantasy V and Dragon Ball Xenoverse 2) have "stun mechanics" that are implemented quite well, and they are often an important aspect of a game's design.

In the case of the vanilla UQM, the green things doing the thing you describe as "stun mechanics" is an important part of the fight, because it's the thing preventing ships from easily approaching the Sa-Matra (except with the Pkunk, which as I've already said is designed to be the solution to the Sa-Matra's puzzle, hence why it's able to avoid all of the weapons easily).

🦇

**Comment by Kruzen** [comment]
1. Sa-Matra is comparable to all AI fights. Because it obeys the same set of rules. You dodge one things and shoot other things. The rest is basically cosmetic but fundamentally the same.
2. I know that and that’s why I left a huge gap between my average performance and the point I can’t beat it.
3. It wasn’t the same fight because I changed things constantly. And I know what works in this fight and what doesn’t.

I think you’re missing the point of what I was trying to achieve - anti-snooze combat with constant maneuvering and where victory is earned by piloting skills, not just by picking the right ship.
Thing is hard but beatable. If you find that frustrating - welcome to the standard difficulty. That’s my creed until some valid points are made. Until that all I’ve seen that you’ve had a bad time and something something puzzle solving mr game designer (assuming a good one).

ps: stuns are bad because they’ve being used without any reason. There is no place for them in fast-paced combat game. So limit them as much as possible. Luckily we have only 2 in base game: vux and mel.
They are fine for some turn-based games

**Comment by onpon4** [comment]
> Sa-Matra is comparable to all AI fights. Because it obeys the same set of rules. You dodge one things and shoot other things. The rest is basically cosmetic but fundamentally the same.

Then you have little appreciation for the combat system. The Star Control combat system isn't just "dodge things and shoot other things", and in fact dodging isn't really a feature in many ships. Far, far more important is how ships interact with the planet, and to a lesser extent, the asteroids; as well as choosing the best possible ship against the ship you're fighting. The Sa-Matra battle has almost nothing in common with normal fights unless, as you've done here, you break it down to such low-level fundamentals that you would say it's fundamentally no different from Asteroids, or heck, even Space Invaders.

Unlike in a standard battle, the Sa-Matra is a battle against a stationary, unmovable set of several distinct targets, with no planet and no asteroids, and with bullets that spawn and follow you endlessly anywhere you go. Most of the obstacle in your way in this scenario isn't the interesting combat mechanics of the various ships, it's just trying to get close enough to the targets you need to shoot without dying by running into the endless bullets that follow you wherever you go. It's an experience far more comparable to a bullet hell game than to Star Control's melee system.

> I think you’re missing the point of what I was trying to achieve - anti-snooze combat with constant maneuvering and where victory is earned by piloting skills, not just by picking the right ship.

I know, and in doing so, you've completely trashed the design of the game at the end. Action combat is not always the best choice gameplay-wise. As I said in the first post, I don't have anything against an action combat final boss, but to do so properly, substantial changes to the way the boss works would probably be needed. The way you did it was with no appreciation for what makes the Sa-Matra fight work in the vanilla game.

> If you find that frustrating - welcome to the standard difficulty. That’s my creed until some valid points are made.

Then you are not fit for game design at all. This sort of arrogance *never* breeds good gameplay. I have a perspective you don't (that of an experienced UQM player who didn't spend weeks on end practicing a very unusual fight), and your entire response here has been to assume that I don't know what I'm talking about and then insist "I'm right and you're wrong, neeener neener" in so many words. When players complain about something, in general, they're not always right about the proper solution, but in 99% of cases there *is* a problem in the design. Part of your job as a game designer is to graciously listen to feedback and make a decision on what design changes to make to solve the problem which is brought up.

> ps: stuns are bad because they’ve being used without any reason. There is no place for them in fast-paced combat game. So limit them as much as possible. Luckily we have only 2 in base game: vux and mel.

No, again, this take is wrong. One of the examples I gave that I rather like is an action combat based game and makes "stuns" a major component of its combat system. You've also now admitted yourself that "stuns" are used in vanilla UQM's basic combat system via the VUX and Melnorme, some of the most interesting ships in the game. The Melnorme and VUX specials aren't some negative that just don't matter much, they are components that form a part of what the game is good. The only truly problematic ship design in the game (as opposed to just ships which have faulty point values or aren't as useful as they ought to be) is the Thraddash, and that ship has no such "stun mechanics".

🦇

**Comment by JHGuitarFreak** [comment]
Regardless, projectile speed is nerf'd and all other hard mode enhancements remain so the projectiles can still kick your ass if you're not quick.

Closing this issue until someone has a better idea.
