### ISSUE TITLE
In hard mode, cost of Melnorme tech is always 50 credits more than I have

### ISSUE THREAD

**Issue by tjareth** [JHGuitarFreak/UQM-MegaMod#167]
I am enjoying hard mode but this is unfortunately making real progress impossible.  After visiting four rainbow worlds and collecting a bunch of aliens, I was only able to buy the double-capacity fuel tanks.  Every other location they say I don't have enough, and when I collect more and return they say I still don't have enough.

**Comment by JHGuitarFreak** [comment]
Oof, that's a good one.

I'll take a look into it when I get more time.

**Comment by JHGuitarFreak** [comment]
I'm not able to replicate this one on my end.

I just want to make sure of something...

The "Unfortunately" line was added to let the player know that the price of the current tech to buy is now higher because you have already bought some tech from them. The price increases with the amount of tech you've purchased multiplied by 50.

Like in this image: 
![2023-06-11_01-18-19 v0 8 3 MegaMod Debug](https://github.com/JHGuitarFreak/UQM-MegaMod/assets/104330805/3675bb61-eb9f-4ba5-86e6-55e61bb17b5d)

It is telling me the current tech is 350 credits _extra_ on top of the base cost of 150 because I have all 7 Lander upgrades (7 * 50 = 350) which is 500 credits in total.

It will still let me buy the current tech at the increased cost:
![2023-06-11_01-22-05 v0 8 3 MegaMod Debug](https://github.com/JHGuitarFreak/UQM-MegaMod/assets/104330805/2b78996c-67b1-4256-b225-c93d0c420db4)

I know that the added line is a bit jank, but this was the best way to do it without resorting to recording new dialogue.

**Comment by tjareth** [comment]
You know what, I never thought of that.  I may have heard that line and gave up to soon each time.  I'll go try it some more.

**Comment by tjareth** [comment]
Follow up:  It just worked fine.  Looks like I was hasty to conclude a bug.  Thank you for your response!

**Comment by JHGuitarFreak** [comment]
> Follow up: It just worked fine. Looks like I was hasty to conclude a bug. Thank you for your response!

Awesome! And you're welcome! Don't be afraid to post more issues if you come up against something. Sometimes you never know.
