### ISSUE TITLE
[feature request] adjust hazardous planet difficulty

### ISSUE THREAD

**Issue by HimoriK** [JHGuitarFreak/UQM-MegaMod#169]
Early on you can't gather resources from some planets due to landers being instantly destroyed from hazards.
I propose to make this less grindy and easier to navigate closer to the early/mid game.  Also, perhaps invoke additional
treasure planets early on since there is a deficit for grinding at the start.

**Comment by JHGuitarFreak** [comment]
This could be a good idea for Easy Mode. Though I don't know how feasible it is to invoke more treasure worlds based on difficulty level.

I'll definitely give it a look.

**Comment by HimoriK** [comment]
I'd suggest it as a cheat, since even though the start isn't terribly bad the upgrades you get for your lander tech require a lot of bio data which you can only get from hazardous worlds unless you use a guide and hope for the best, maybe even 1 treasure world could make a difference. Hm, the difficulty is more based on luck/game knowledge rather than outfitting your starship properly due to upgrade paths being locked in an odd order (weapons before lander?) You would think this would be reversed to encourage exploration to gather resources.

**Comment by JHGuitarFreak** [comment]
The problem with it being a cheat is that messing with treasure world "invocation" messes with the ProcGen code, which could lead to missing planets and even hard crashes when enabling/disabling the option.
Stuff that messes with the ProcGen have to be saved to the save file so that nothing either disappears or appears out of nowhere.  
And the easiest and most logical way to do that would be under the Easy Mode code.

A much simpler solution would be to turn the Infinite RU cheat on for a short period and then turn it off once you feel like you've gotten far enough past the grind.

**Comment by JHGuitarFreak** [comment]
The more I think about it the more this doesn't make sense in the context of MegaMod.  
There are already cheat options that can alleviate the early game grind.  
God Mode (Invulnerability) can help when dealing with hazardous planets or Infinite RU to skip the opening grind entirely.

So I'm closing this for the time being.
