### ISSUE TITLE
Linux flatpak

### ISSUE THREAD

**Issue by electronstudio** [JHGuitarFreak/UQM-MegaMod#212]
I have built a flatpak for Linux, in order to play on my Steam Deck.  Can I have your permission to publish it on Flathub so other people can use it?

https://github.com/electronstudio/UQM-MegaMod-flathub/tree/UQM-MegaMod

**Comment by JHGuitarFreak** [comment]
Before you pull the trigger on something like this I actually need to have a word with the original developers about distributing a version of their game on that platform. Both the UQM and Pistol Shrimp teams.  
It's not really up for me to say that you or I can.  
I see that the original version isn't up there so they may want to get theirs up there first.  
Although they may not since [they're releasing the original on Steam in the future.](https://store.steampowered.com/app/2645580/Free_Stars_The_UrQuan_Masters/)

**_If_** they do end up giving me the go ahead to distribute MegaMod as its own entity then I'd want to be in control of the distribution. That way any bug reports or problems come back to me and I know where they're coming from.

We just need a little patience while I contact the teams because I think it would be great to have UQM on Flathub.

**Comment by electronstudio** [comment]
Flathub prefer to have the cooperation of the project maintainer (i.e. you) because it makes sense for the same person to be managing releases on GitHub and Flathub. As you say, you don’t want bug reports caused by a bad Flathub build that you can’t fix.

Thus after the Flathub release repo is setup I would ask them to transfer control to you. (Or you can do the initial application rather than me if you prefer. )

But not every project on Flathub has this, provided the project has a license that allows redistribution. They certainly don’t require permission from other projects that a project was forked from. 

I believe the original UQM project that your project was forked from was GPL and CC licensed? If so, that’s your legal permission to distribute. They have already given it. (And if not, then you don’t have permission to distribute on GitHub and Sourceforge either.) I’m not suggesting putting the original UQM on Flathub, just your fork of it.

**Comment by electronstudio** [comment]
In the meantime, I've put a bundle of the flatpak here so it can be installed manually https://github.com/electronstudio/UQM-MegaMod-flathub/releases

(It won't auto update like it would if it was on Flathub though.)

**Comment by JHGuitarFreak** [comment]
At any rate I got the go-ahead.

So, a couple questions beforehand...  

Does the flatpack have to be so large?

Also, shouldn't the desktop shortcut version also mirror the application version?

You can go ahead and start the process.  
Looking at how it's done I don't want to have to deal with it at least until v0.8.3 is ready to go.

**Comment by electronstudio** [comment]
Cool, thanks!

The flatpak contains all 5 'basic content' packages, which is why it's that size.  I assume most people are going to want them all, and if they don't they can disable them in the game, so it wouldn't make sense to split them up into separate installs.  (And when you install a flatpak it actually downloads a Linux runtime as well, which adds another gigabyte or two, so Flatpak users are used to big downloads.)

The desktop shortcut is interesting...

The existing desktop shortcut does have "Version: 0.8.2" but because of this it can't be used - it fails Flatpak validation.  The reason for that is that the "Version" field does *not* refer to the version of the application, it refers to the version of the freedesktop spec in use.  So I made the new desktop shortcut.

I can do a PR for you to fix the desktop shortcut.  Also Flathub would ideally prefer that you put the appdata.xml file in the repo along with the sourcecode, so I can do that a PR for that.  But those changes would be for 0.8.3.

**Comment by JHGuitarFreak** [comment]
Desktop shortcut isn't too much of a problem but go on ahead for the appdata.xml.

**Comment by electronstudio** [comment]
It's up at https://flathub.org/apps/net.sourceforge.uqm_mods.UQM-MegaMod . I've asked them to give you access.
