### ISSUE TITLE
Crash out of memory, (netplay?)

### ISSUE THREAD

**Issue by Sashachan** [JHGuitarFreak/UQM-MegaMod#24]
Im randomly getting crashes when starting interaction with aliens or checking planets.

The crash message is
```
The Ur-Quan Masters encountered a fatal error.

Part of the log follows:

The Ur-Quan Masters v0.8.0.84 MegaMod (compiled Sep 15 2019 16:57:39)
This software comes with ABSOLUTELY NO WARRANTY;
for details see the included 'COPYING' file.

Netplay protocol version 0.4. Netplay opponent must have UQM 0.8.0.84 or later.

HMalloc() FATAL: out of memory.
```

I have no idea what this Netplay is, as im playing normal campaign. It kinda sucks, because i lost a lot of progress because there is no autosave ;/
Any ideas what what is causing this?

//Edit
I noticed there is .85 version on the github that i didn't saw on the main site, is this problem fixed in that version?
Im using win10 and .84 version of megamod

**Comment by Serosis** [comment]
The Netplay message is always there to tell you what version of UQM you can link up to.

> HMalloc() FATAL: out of memory.

***That*** is the error. And 0.8.0.85 *may* have fixed some of the memory issues.
I know a major one was fixed with the Hyperspace music code that caused crashes exactly like yours.

0.8.0.85 isn't ready for release just yet. Got a couple more things to do and I'm still waiting to see when the new core UQM version releases.
