### ISSUE TITLE
Druuge AI don't use thrust during melee in HD

### ISSUE THREAD

**Issue by Kruzen** [JHGuitarFreak/UQM-MegaMod#51]
I've made some tests with druuge and found out that they don't use thrust during melee. It happens in main game and in Super-melee. Only in HD for some reason, original gfx works fine. 

Sidenote: it actually makes fighting them a bit harder as they shoot 3-4 times and you have a seizure from how fast screen is changing.

**Comment by Serosis** [comment]
Now that's an odd one. Confirmed on my end as well.

I'll look into the AI code to see what's happening.

EDIT:
Checked in Vanilla HD-mod and they move around just fine before shooting so I may have left something out when I ported HD to v0.8.0 originally.

UPDATE:

Fixed with commit 17ac42090aafa95a6d5a8deefb6620eb3525e97c
