### ISSUE TITLE
[feature request] add log planet in-game menu

### ISSUE THREAD

**Issue by nsklaus** [JHGuitarFreak/UQM-MegaMod#52]
it would be nice if we could have a new in-game menu entry to allow us to log planets.
- a simple version could be for example, just to log interresting planets, to be able to remember them, and come back to them later. when lander gets stronger.
- a more complex version could be to also allow player to track all planets that have been stripped clean, so we don't come back countless time to re-check and discover we already did that planet and it was pointless to come back to it. in that "more complex version" there could be a visual cue somewhere in the ui (both in starmap view and in planetary system view) that tells about planets that have already been cleared. 
in starmap view when pointing at a system that has been entirely cleared, it could show that visual cue next to their names.  in planetary-view, maybe a toggleable "X" overlaying planets themselves. so we'd know at a glance what's been done and what's left to check.

**Comment by nsklaus** [comment]
actualy, on a second tought, the log system should also log quests.
maybe it could have tabs, like:

a tab for recording game's events and progress, fully automated, that gets populated with player's actions, like achievements, getting a new quest, progressing through quest in steps, or completing quests. 
this would be much needed as right now i see the player gets a lots of different objectives and directions to investigate, but it all have to be memorized or written down on a piece of paper to be able to remember them all.

another tab could be for planet logging. as detailed in opening post.

eventualy a 3rd tab for codex, this should help on building and expanding lore, giving more detailled informations about the different races as we meet them, and also game's objects such as artefacts, ship's modules, weapons, add-ons and etc..

i could make mockup of the different tabs if you find the idea interesting.
every ship captain needs a log, starting with: "captain's log, stardate `insert number`   :)

**Comment by atfrase** [comment]
Funny, I just had exactly this same train of thought the other day -- about logging remaining resources, then logging quests and other info about aliens, artifacts, etc.

I've started hacking together an in-game Journal, accessible from the menu just like the Starmap. So far it just tracks the goals and tasks related to getting the Starbase repaired and recruited, but it seems to work:
![journal-sample-1](https://user-images.githubusercontent.com/238400/155445860-3831d644-ec74-48af-b4af-13699d27f5ba.png)

Most of the other major game quests can probably also be handled already with existing game state flags, but for alien facts (i.e. learning progressively more about them -- name, general area, home constellation, home star, orbital, homeworld name, etc) and other clues and leads mentioned in conversation, I'll have to add a ton more flags and hunt down all the conversation lines that should set them.

I'll also need to decide where to put all the strings. I could just throw them all onto the end of GameStrings, but there are likely to be *so many* strings involved in this feature that I wonder if I should create a new string resource file just for that purpose. That file could then also be part of an addon, so the entire Journal feature and menu item disappears if not installed.

Anyway, feedback welcome!

**Comment by Serosis** [comment]
That actually looks really good.

As far as strings go, yeah, a new resource would be preferred just for organization.
Gamestrings is already jam packed with everything _but_ the Setup Menu strings.

Though I'm having some trepidation about activating it via the menu.  
Adding another entry to the menu that wasn't in the original games feels wrong.
Heck the "Reading" functionality we added back in for v0.8.1 feels wrong.

I'm thinking it would be better activated as a key press, like modern games usually have Tab as the activator.  
Though you'd have to disable the Journal when doing star search as the Tab key is used to switch between different stars within a constellation.

And activating via key press gives the advantage of being able to read the Journal mid-conversation.
Like if for some reason you forget the Spathi cipher you could open the Journal without having to end the conversation.

But that's the only constructive criticism I have, the rest of the ideas and implementation you've done so far are amazing.

**Comment by taleden** [comment]
Oops, didn't notice I posted that earlier comment from the wrong account. =P

Yeah, gamestrings is pretty overloaded. And because of the way the in-game menus are drawn, new menu entry strings must be inserted in-order in the middle of the MAINMENU_STRING_BASE section; but because MegaMod stuck a bunch of launcher setup strings at the end of that section (and some randomly in the middle), all those offsets then had to be updated. So instead, as part of this project I took them out of the menu section and moved them to their own MEGAMOD_STRING_BASE section at the end of gamestrings, so that their offsets will be more stable.

About adding a menu entry in the first place, if this were the upstream UQM project I'd entirely understand, since their priority is faithful reproduction of the original releases with only the most necessary bug fixes and a few minor stealth features. Personally I wish they'd consider adding things like this Journal and a lot of what you've packaged here -- improved autopilot, partial mineral pickup, HD graphics -- that are completely in line with the style and design of the game and probably would have been original features if they'd been technically/logistically feasible 30 years ago. It's easy enough to ask the player if they want the retro or updated experience, after all.

But to my mind, given UQM's much more conservative approach, the big value of something like your MegaMod is to add these kinds of mostly seamless QOL features so that the game is more accessible for modern players. Particularly for a feature like this, to help new players (who do not yet have memorized all of the sometimes non-obvious things they have to do to progress the story) to enjoy this game, hiding it behind a special key with no on-screen prompt (and probably also completely inaccessible for gamepad controller users) seems unnecessary.

I mean, you've already added in brand new "extended lore" story writing that didn't exist in any of the original releases, is a menu entry really a greater departure from the source? =D It's your mod project, of course, so it's your call, but there's my $.02. :)

It would be cool if it were useful to pull up the journal mid conversation, but I'm not sure it really would be, since it's not like you ever have to type in some piece of knowledge -- the game already knows whether you've acquired the Spathi Cipher (for example) and gives you that speech option whether you personally remember it or not. So far it's accessible in all the places the Starmap is -- orbit, interplanetary, and hyperspace -- but I've considered adding it to the encounter menu too, so you could review data about a species before deciding whether to converse or attack, for example.

Anyway, I'll keep working on adding all the necessary flags and journal entries.

(Also, @nsklaus , let me know if you'd rather I open a new issue for this development; I figured I should acknowledge that you'd suggested this feature long before I ever thought of it, but I don't want to hijack your thread.)

**Comment by nsklaus** [comment]
@taleden 
hi, it's not my mod, i'm not the author, i'm just a user.
and, there's no hijacking, i just submited an idea, anyone is free to build on it and expand. i looked at the screenshot you had posted earlier and did find it was a good step in the right direction. please feel free to take my idea for yourself and offer your own take on implementing it in any way you see fit. 

since i'm here, i would like to say,
star control2 and UQM in general feel like a skeleton of a game. everything basic is there to make a good game, all the fundations are there, but should be expanded upon.
for example, planet exploring and mining is bland and boring. there should be lots of in-game "mini-games" added.
like:
- more challenging landing (include the management of gravity, weather, visibility, player should fight against those, to land properly)
- more challenging mining (drill should have a chance to break or fail, drilling should take a small amount of time to succeed like a process .. put a drilling progression bar.. drilling spots should be shown as a small coloration of the terrain, instead of just displaying some colored sphere .. maybe lander should have onboard radar, with limited radius, and have the player run radar scans of surroundings, makes the player search a bit, give him general direction for probable resources then player should make drill attempt, fail, move a bit, test drilling again.. make few drill attemps around an area shown by radar to finaly find the goods)
- more challenging planet surface exploration: (according to gravity and weather, lander fuel consumption should vary. strong winds = more fuel... also winds should push off lander a bit to offer movement resistance, friction..
- more beautiful planet surface exploration: show nicer weather, dust storm, clouds, darkness cycle, display thickness of atmospheric conditions by using colors tint layer of varying density..
etc , etc...
there's so much nice stuff that could be added to this game to make it more interesting.

**Comment by maxius4** [comment]
i like it perfect for new people that you want to intro to the world now if
we can just get SC1 shoehorned into sc2 :D

**Comment by Serosis** [comment]
If you're insistent on the menu then I should forewarn you that it's going to be torn apart and remade to DOS specs for v0.8.2.

Since the current PC menu is somewhat reliant on the 3DO menu, I want to break that reliance and make it two separate menus.

**Comment by taleden** [comment]
I'd say it's not that I'm insistent on a menu per se, it's just that it seems to me that in a mod (or mod pack, as it were) that a user must explicitly choose to download, install and activate, there's no reason for the features of that mod to hide and try to pretend they aren't there unless the user knows the special secret access key. Instead, I'd rather design the feature to be obvious but seamless, as if it were always an original feature of the game, and I think if TFB had implemented a journal it almost certainly would have been accessible via the game menu just like everything else.

That said, I'm totally open to thoughts about where in the menu it best belongs. I considered putting it under Manifest, for example, but it didn't seem like a good fit there since the Journal doesn't involve physical items/crew on the ship like everything else in Manifest. I also thought about converting Starmap into a two-level menu called something like 'Data' or 'Database' that would include both the starmap and the Journal, but I didn't want to disrupt peoples' muscle memory (Starmap being the first menu item and probably by far the most frequently accessed, I'm certainly in the habit of rapidly pressing the two keys to open it and would be thrown off by the addition of another menu layer; also, it'd be a silly submenu of only two items).

The current PC/3DO menu design is pretty futzy, I agree, but it should be no problem to adjust for however you decide to reimplement it.

**Comment by Serosis** [comment]
You really think I would set the function as a key and just not tell anybody?  
It's a major feature, there would be an in-game prompt just like the StarMap keys.  
Not to mention all the release material would mention it.

But for now, it's fine where it is.

**Comment by taleden** [comment]
Apologies, I realize reading that back that it sounded a lot more prickly than I meant it. =D

Meanwhile, I've been looking at how to add the state flags that will be needed to track some tasks and other clues given in conversations, and I notice that the game state system in MM has become... a little messy. :) Would you be opposed to a separate PR to try to streamline the versioning/saving/loading of game state flags?

**Comment by Serosis** [comment]
If you mean somehow stripping down the game state bitmaps then I'm all for it as long as the functionality is the same.

**Comment by Serosis** [comment]
Oh, also, if you absolutely need to add new gamestates for the journal you can use the reserved bits. That's what they were there for.

**Comment by JHGuitarFreak** [comment]
I made a somewhat relatable function to the first request where you can add a reticule over stars on the starmap. So far it's pretty basic with only a single type of reticule. I figured it could be used to mark stars of interest or really anything you'd want to mark a star for.
![2022-07-11_03-53-29 v0 8 2 MegaMod Debug](https://user-images.githubusercontent.com/104330805/178249052-d099a76b-be3e-4532-bd92-989887e7993b.png)
