### ISSUE TITLE
Sa-Matra has its name only after Save/Load

### ISSUE THREAD

**Issue by Kruzen** [JHGuitarFreak/UQM-MegaMod#58]
Will show only screenshots.

If we play normally, it says Planet V (also shows RU for some reason):
![image](https://user-images.githubusercontent.com/68859542/90687197-26e7d500-e275-11ea-83b4-4dd8b40dcf70.png)

If we Save and Load:
![image](https://user-images.githubusercontent.com/68859542/90687263-454dd080-e275-11ea-845d-a12d97ce981d.png)

I sadly have no idea how to fix it. Probably something between encounters must be tweaked.

**Comment by Serosis** [comment]
That's interesting because the name doesn't show up for me either way.

I'll look into it.

UPDATE:

I believe it has something to do with it being a moon but for appearances only.

**Comment by Serosis** [comment]
As an aside I want to add that visiting the Sa-Matra the first time yields an encounter screen that shows Planet V instead of the Sa-Matra itself.

![image](https://user-images.githubusercontent.com/4404965/90827100-74edee80-e2f0-11ea-82fa-c408e95ee234.png)

I wonder if this can be smoothed into showing the Sa-Matra so that things can be congruent.

**Comment by Serosis** [comment]
I've fixed this as well as added new functionality for Extended Lore with commit 136903d352095355abc30d31ecfe17f340cc6c0b
![image](https://user-images.githubusercontent.com/4404965/90953487-c2697900-e420-11ea-99e7-60387ee22f24.png)

**Comment by Kruzen** [comment]
Nice! Closing issue
