### ISSUE TITLE
Interplanetary music issue (Volasaurus interplanetary pack/remixes)

### ISSUE THREAD

**Issue by Kruzen** [JHGuitarFreak/UQM-MegaMod#62]
If we Load Game from Sa-Matra pre-attack screen:

![image](https://user-images.githubusercontent.com/68859542/90800104-dc219800-e31c-11ea-82aa-ff2c99998103.png)

and loaded game will be in interplanetary during Kohr-Ah march, instead of _<WE'RE ALL GONNA DIE>_ track (I guess it's labeled as Kohr-Ah interplanetary) a standart one will be played

**Comment by Serosis** [comment]
That's interesting because the name doesn't even show up for me either way.

I'll look into it.

**Comment by Serosis** [comment]
I can't seem to replicate this.

To clarify... I'm loading a game saved at the Sa-Matra first *then* loading a game saved mid-Death March while in interplanetary?

If that's the case then it's working fine for me. 
It may have been fixed with Ala-lala's SOI music memory leak fix on the old repository.

**Comment by Kruzen** [comment]
Yep, I thought so when I looked through changelog. If it's working fine on your end then case closed.
