### ISSUE TITLE
Master build: Textured planets show when suppose to be disabled

### ISSUE THREAD

**Issue by JoshuaPettus** [JHGuitarFreak/UQM-MegaMod#67]
When you arrive on a planet with the lander and textures are disabled, you will see a textured planet.
When textures are enabled and you arrive with the lander, the planet texture doesn't display.

This happens in both HD and Original.

**Comment by Serosis** [comment]
I'm not able to replicate this on my end.

Can you upload a couple screenshots to show what's happening?

**Comment by JoshuaPettus** [comment]
Sorry, it was late and wanted to get it in before I forgot :)

So there are a few things going on here

Here is what it looks like with the Planet textures on.

![With Textures On](https://user-images.githubusercontent.com/5043172/94021195-bf480c80-fd81-11ea-9d76-c2a9b2e04e61.png)

Which is to be expected except for the planet texture not rendering.  Maybe it's an issue with my content files.  I pulled and installed from the latest master of your content from github, and used the planet textures file from 0.8.0.84.  Maybe that was a mistake?

But then when planet textures are off I get the same exact thing

![With Textures Off](https://user-images.githubusercontent.com/5043172/94021572-28c81b00-fd82-11ea-9dad-04ac86c4888d.png)

Shouldn't it look like this from the original pc game?

![Origional](https://user-images.githubusercontent.com/5043172/94021630-37aecd80-fd82-11ea-9eb6-4450d8f3ae92.png)

I forgot how minerals were in different locations in the original pc game.  I take it these locations are from the 3do?

**Comment by Serosis** [comment]
Ooooh, You mean the SOL textures.

While they're installed they take precendence over the setting. But they're not supposed be blank while landing.

**Comment by JoshuaPettus** [comment]
I guess that makes sense.  i guess I expected more from that setting to go back to classic planets including the SOL textures

**Comment by Serosis** [comment]
Fixed with commit ad5c2bde2fbf39e2363e55c0f61e64735155166f

**Comment by Serosis** [comment]
Oh, and an answer to the mineral locations...

PC/3DO and UQM mineral amounts and locations will be different due to how the procedural generation relies on screen size.

It's very fascinating how the littlest change will skew the results: 
3DO Screenshot
![image](https://user-images.githubusercontent.com/4404965/94165117-bb2df480-fe3e-11ea-87c4-b898417f8270.png)

You'll notice even the background stars and planet topology is different:
![image](https://user-images.githubusercontent.com/4404965/94165322-f0d2dd80-fe3e-11ea-83ad-6fb8e6a54274.png)

**Comment by JoshuaPettus** [comment]
Oh wow, that is really neat!  thanks for going into the effort for making pictures!
