### ISSUE TITLE
Game freezes upon entering system [reproducible]

### ISSUE THREAD

**Issue by dmn777** [JHGuitarFreak/UQM-MegaMod#79]
Hi all,
Just tried this mod and it looks really nice. However, entering Alpha Centauri in the attached save consistently freezes the game. I have tried varying my game settings, but the issue remains.

The savegame is made right next to Alpha Centauri for ease of reproducing the issue.

Megamod version: v0.8.0.85

[uqmsave.zip](https://github.com/Serosis/UQM-MegaMod/files/6857903/uqmsave.zip)

**Comment by Serosis** [comment]
Ooof, this is definitely a serious one. I can see you're using seed 16806 so definitely tied to the custom seed system.

This is even affecting the latest version of the code so I'll have to deep dive into it.

Thanks for attaching such an easy save for reproducing this bug.

**Comment by dmn777** [comment]
Thank you for looking into it. I look forward to either continuing my playthrough or starting a new one once the issue is solved. :)

Please let me know in case you need any further information besides the save.

**Comment by Serosis** [comment]
The bug is fixed with commit fbde1f395333da7b107481dc375dd68aa45ca074 but it won't appear until the next release.  
My advice is to see if you can avoid Alpha Centauri for the time being.

Or... Here, I hex edited your save file to change the seed to 16808
[uqmsave.zip](https://github.com/Serosis/UQM-MegaMod/files/6866259/uqmsave.zip)

Hopefully it doesn't happen in that seed.

**Comment by dmn777** [comment]
Cool! Thanks a lot for adjusting the save, that helps. :)
Looking forward to the next release where this will be fixed for good.
