### ISSUE TITLE
Issue with build script on linux

### ISSUE THREAD

**Issue by JPT77** [JHGuitarFreak/UQM-MegaMod#80]
build.sh wants to copy files from src/content to share/uqm-megamod/content. But src/content does not exist in the source.zip file. Please add directions in the INSTALL readme. At least how to put the VERSION file and the main CONTENT file into content dir manually.

There are typos in the installsome() function in build_functions file. parameter is named OWNDER instead of OWNER (2 occurences). So the owner probably wont be ever set correctly. This wasn't cause of my problems. Beware of scripting w/o proper variable declaration!

**Comment by Serosis** [comment]
Oh man, thanks for letting me know, I also saw that you posted a few messages in the official UQM IRC channel.

I must have completely spaced out that you need to clone the Content repo into the root of the Source repo then rename `UQM-MegaMod-Content` to `content`. 
I split it to save the source repo from long commit times due to the size of the content files.

Perhaps I can add in a preparation script that can be ran before compile time.

"OWNDER" seems to also be a vanilla UQM issue as well as it's in their repo. I made sure to double back in the IRC channel to let them know.

UPDATE:

I can't really make heads or tails of the build script. On one hand I can get it to work, on the other I don't know how to run MegaMod after it is installed.

Are apps or games even installed like this anymore?
Deep into the bowels of the file system where you need root permissions to make any changes?

**Comment by CelticMinstrel** [comment]
> you need to clone the Content repo into the root of the Source repo

Why not use git submodule?

**Comment by Serosis** [comment]
I don't entirely know how Git works.

So far I've only figured out the surface level stuff like branches, forks, and pull requests.
The rest of my Git knowledge lies within GitKraken.

UPDATE:

I just looked into it and submodules are bad-ass.
Definitely the way to go moving forward.

UPDATE:

Nevermind about the submodule thing.
Slows my repository ***way*** down, much more so than if I included the content in the main repo in the first place.

**Comment by Serosis** [comment]
I've simply added the version file to this repository to satisfy the build script when no content is present.

Closing the issue for now until I can think up a more elegant solution.

**Comment by JPT77** [comment]
`build.sh uqm` builds
`build.sh uqm install` installs

I install into ~/local so I don't need any root permissions. This didn't work out of the box either because build.sh did not expand ~ to the users home dir. but this is the same for plain uqm. so I had to use /home/myuser/local instead.

You need to have your ~/local/bin (or your installation path/bin) in $PATH if you want it to be found when run from console. I don't think that /usr/local/games/bin is included in the PATH. so that might be the problem why you cannot simply run it after installation.

**Comment by JPT77** [comment]
This is a good idea. this way the build script does not fail any more with unclear reason. That you have to install the uqm files manually somehow should be clear if you deal with installing the game.

**Comment by Serosis** [comment]
> `build.sh uqm` builds
> `build.sh uqm install` installs
> 
> I install into ~/local so I don't need any root permissions. This didn't work out of the box either because build.sh did not expand ~ to the users home dir. but this is the same for plain uqm. so I had to use /home/myuser/local instead.
> 
> You need to have your ~/local/bin (or your installation path/bin) in $PATH if you want it to be found when run from console. I don't think that /usr/local/games/bin is included in the PATH. so that might be the problem why you cannot simply run it after installation.

I've been toying around with the build script and you'd need to use `$HOME` to get your current profile folder.

I'll add a note to download the content files when building from scratch in one of the readme files.

UPDATE:

I updated the INSTALL file with a brief instruction on what to do about the content: a4f893b7292ed437b61685eb7b273b3f7f7be8de

**Comment by JoshuaPettus** [comment]
~/  only means something to the BASH shell.  You get into trouble sometimes in scripts hence why you need to use $HOME
